print('**EXERCICIO 4**\n')
x = input('Digite algo: ')
print('O tipo primitivo desse conteúdo é {}: '.format(type(x)))
print('O conteúdo digitado possui espaços: ',(x.isspace()))
print('O conteúdo digitado é alfabético: ',(x.isalpha()))
print('O conteúdo digitado é maiúsculo: ',(x.isupper()))
print('O conteúdo digitado é minúsculo: ',(x.islower()))
print('O conteúdo digitado são números: ',(x.isnumeric()))
print('O conteúdo digitado é alfanumérico: ',(x.isalnum()))
print('O conteúdo digitado esta capitalizada(mista): ',(x.istitle()))


print("O conteúdo digitado são números? {}".format(x.isnumeric()))
print("É alfanumérico? {}.".format(x.isalpha()))
print("O conteúdo digitado é alfabético? {}.".format(x.isdecimal()))
print("Está em caixa baixa? {}.".format(x.islower()))
print("O conteúdo digitado possui espaços? {}.".format(x.isspace()))
print("O conteúdo digitado é minúsculo? {}.".format(x.islower()))
print("O conteúdo digitado é maiúsculo? {}.".format(x.isupper()))